/home/ywatanabe/proj/mngs/src/mngs/general/_converters.py:75: UserWarning: Converted from  <class 'numpy.ndarray'> to <class 'torch.Tensor'> (cpu)
  warnings.warn(
Traceback (most recent call last):
  File "/home/ywatanabe/proj/entrance/mngs/dsp/_wavelet.py", line 57, in <module>
    axes[0].plot(tt, xx[0, 0], label="orig")
  File "/home/ywatanabe/proj/mngs/src/mngs/plt/_subplots.py", line 175, in wrapper
    result = original_attr(*args, **kwargs)
  File "/home/ywatanabe/proj/mngs/src/mngs/dsp/env/lib64/python3.9/site-packages/matplotlib/axes/_axes.py", line 1724, in plot
    lines = [*self._get_lines(self, *args, data=data, **kwargs)]
  File "/home/ywatanabe/proj/mngs/src/mngs/dsp/env/lib64/python3.9/site-packages/matplotlib/axes/_base.py", line 303, in __call__
    yield from self._plot_args(
  File "/home/ywatanabe/proj/mngs/src/mngs/dsp/env/lib64/python3.9/site-packages/matplotlib/axes/_base.py", line 499, in _plot_args
    raise ValueError(f"x and y must have same first dimension, but "
ValueError: x and y must have same first dimension, but have shapes (4096,) and (2, 4096)
